sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t firpaw2020dockerlabs/lab:test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true firpaw2020dockerlabs/lab:test npm test

after_success:
  - docker build -t firpaw2020dockerlabs/lab:fib-client ./client
  - docker build -t firpaw2020dockerlabs/lab:fib-nginx ./nginx
  - docker build -t firpaw2020dockerlabs/lab:fib-server ./server
  - docker build -t firpaw2020dockerlabs/lab:fib-worker ./worker
  # Logowanie do docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push obrazow do docker hub
  - docker push firpaw2020dockerlabs/lab:fib-client
  - docker push firpaw2020dockerlabs/lab:fib-nginx
  - docker push firpaw2020dockerlabs/lab:fib-server
  - docker push firpaw2020dockerlabs/lab:fib-worker
